// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee interface {
	IsEmployee()
}

type ContactInfo struct {
	PhoneNumber  string `json:"phoneNumber"`
	EmailAddress string `json:"emailAddress"`
}

type ContactInfoInput struct {
	PhoneNumber  string `json:"phoneNumber"`
	EmailAddress string `json:"emailAddress"`
}

type Customer struct {
	ID          string       `json:"id"`
	FirstName   string       `json:"firstName"`
	LastName    string       `json:"lastName"`
	ContactInfo *ContactInfo `json:"contactInfo"`
}

type CustomerFilter struct {
	LastName     *string `json:"lastName"`
	PhoneNumber  *string `json:"phoneNumber"`
	EmailAddress *string `json:"emailAddress"`
}

type CustomerInput struct {
	ID          string            `json:"id"`
	FirstName   string            `json:"firstName"`
	LastName    string            `json:"lastName"`
	ContactInfo *ContactInfoInput `json:"contactInfo"`
}

type InventoryItem struct {
	ID           string        `json:"id"`
	Description  string        `json:"description"`
	Cost         float64       `json:"cost"`
	Retail       float64       `json:"retail"`
	Manufacturer *Manufacturer `json:"manufacturer"`
}

type InventoryItemInput struct {
	ID           string             `json:"id"`
	Description  string             `json:"description"`
	Cost         float64            `json:"cost"`
	Retail       float64            `json:"retail"`
	Manufacturer *ManufacturerInput `json:"manufacturer"`
}

type LineItem struct {
	Description string  `json:"description"`
	Retail      float64 `json:"retail"`
	Quantity    int     `json:"quantity"`
}

type LineItemInput struct {
	Description string  `json:"description"`
	Retail      float64 `json:"retail"`
	Quantity    int     `json:"quantity"`
}

type Manager struct {
	ID        string `json:"id"`
	StoreID   string `json:"storeId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
}

func (Manager) IsEmployee() {}

type ManagerInput struct {
	ID        string `json:"id"`
	StoreID   string `json:"storeId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Manufacturer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ManufacturerInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewCustomerInput struct {
	FirstName   string            `json:"firstName"`
	LastName    string            `json:"lastName"`
	ContactInfo *ContactInfoInput `json:"contactInfo"`
}

type NewInventoryItemInput struct {
	Description  string             `json:"description"`
	Cost         float64            `json:"cost"`
	Retail       float64            `json:"retail"`
	Manufacturer *ManufacturerInput `json:"manufacturer"`
}

type NewManagerInput struct {
	StoreID   string `json:"storeId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type NewManufacturerInput struct {
	Name string `json:"name"`
}

type NewOrderInput struct {
	CustomerID       string           `json:"customerId"`
	StoreID          string           `json:"storeId"`
	SalesAssociateID string           `json:"salesAssociateId"`
	LineItems        []*LineItemInput `json:"lineItems"`
}

type NewSalesAssociateInput struct {
	StoreID   string `json:"storeId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type NewStoreInput struct {
	Name     string              `json:"name"`
	Location *StoreLocationInput `json:"location"`
}

type Order struct {
	ID             string          `json:"id"`
	StoreID        string          `json:"storeId"`
	Customer       *Customer       `json:"customer"`
	SalesAssociate *SalesAssociate `json:"salesAssociate"`
	LineItems      []*LineItem     `json:"lineItems"`
}

type OrderInput struct {
	ID               string           `json:"id"`
	CustomerID       string           `json:"customerId"`
	StoreID          string           `json:"storeId"`
	SalesAssociateID string           `json:"salesAssociateId"`
	LineItems        []*LineItemInput `json:"lineItems"`
}

type SalesAssociate struct {
	ID        string `json:"id"`
	StoreID   string `json:"storeId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
}

func (SalesAssociate) IsEmployee() {}

type SalesAssociateInput struct {
	ID        string `json:"id"`
	StoreID   string `json:"storeId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Store struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Location *StoreLocation `json:"location"`
}

type StoreFilter struct {
	Name  *string `json:"name"`
	City  *string `json:"city"`
	State *string `json:"state"`
}

type StoreInput struct {
	ID       string              `json:"id"`
	Name     string              `json:"name"`
	Location *StoreLocationInput `json:"location"`
}

type StoreLocation struct {
	Street  string `json:"street"`
	City    string `json:"city"`
	State   string `json:"state"`
	ZipCode string `json:"zipCode"`
}

type StoreLocationInput struct {
	Street  string `json:"street"`
	City    string `json:"city"`
	State   string `json:"state"`
	ZipCode string `json:"zipCode"`
}
