CREATE TABLE IF NOT EXISTS ContactInfo(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    EmailAddress TEXT NOT NULL UNIQUE,
    PhoneNumber TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Customer(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    ContactInfoId INTEGER NOT NULL,
    FOREIGN KEY (ContactInfoId) REFERENCES ContactInfo(Id)
);

CREATE TABLE IF NOT EXISTS StoreLocation(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Street TEXT NOT NULL,
    City TEXT NOT NULL,
    State TEXT NOT NULL,
    ZipCode TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Store(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    LocationId INTEGER NOT NULL,
    FOREIGN KEY (LocationId) REFERENCES StoreLocation(Id)
);

CREATE TABLE IF NOT EXISTS Manager(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    StoreId INTEGER NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Password TEXT NOT NULL,
    FOREIGN KEY (StoreId) REFERENCES Store(Id)
);

CREATE TABLE IF NOT EXISTS SalesAssociate(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    StoreId INTEGER NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Password TEXT NOT NULL,
    FOREIGN KEY (StoreId) REFERENCES Store(Id)
);