CREATE TABLE IF NOT EXISTS ContactInfo(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    EmailAddress TEXT NOT NULL UNIQUE,
    PhoneNumber TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Customer(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    ContactInfoId INTEGER NOT NULL,
    FOREIGN KEY (ContactInfoId) REFERENCES ContactInfo(Id)
);
